name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2020.12.31
    - run: pip install poetry==1.1.5
    - run: pip install nox-poetry==0.7.0
    - run: nox
  coverage:
    runs-on: ubuntu-latest
    name: Coverage Python 3.9
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install nox==2020.12.31
    - run: pip install poetry==1.1.5
    - run: pip install nox-poetry==0.7.0
    - run: nox --sessions coverage-3.9
